version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

    # Instala dependências PHP e Laravel
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y zip unzip git curl libpng-dev libonig-dev libxml2-dev libzip-dev &&
        docker-php-ext-install pdo_mysql mbstring zip exif pcntl &&
        curl -sS https://getcomposer.org/installer | php &&
        mv composer.phar /usr/local/bin/composer &&
        if [ ! -f /var/www/artisan ]; then
          composer create-project --prefer-dist laravel/laravel .;
        fi &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel: